USE yuban;

CREATE TABLE Users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    passwordHash VARCHAR(100) NOT NULL
);

CREATE TABLE Groups (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    groupname VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE GroupMembership (
    userid INT UNSIGNED NOT NULL,
    groupid INT UNSIGNED NOT NULL,
    FOREIGN KEY (userid) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (groupid) REFERENCES Groups(id) ON DELETE CASCADE,
);

CREATE TABLE Tokens (
    userid INT UNSIGNED NOT NULL UNIQUE,
    token BINARY(32) NOT NULL,
    issuedate TIMESTAMP NOT NULL,
    FOREIGN KEY (userid) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Threads (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    creator INT UNSIGNED NOT NULL,
    group INT UNSIGNED NOT NULL,
    opened_on TIMESTAMP NOT NULL,
    FOREIGN KEY (creator) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (group) REFERENCES Groups(id) ON DELETE CASCADE
);

CREATE TABLE Posts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userid INT UNSIGNED NOT NULL,
    postdate TIMESTAMP NOT NULL,
    post TEXT NOT NULL,
    FOREIGN KEY (userid) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Originals (
    thread_id INT UNSIGNED NOT NULL,
    post_id INT UNSIGNED NOT NULL PRIMARY KEY,
    langcode VARCHAR(2) NOT NULL,
    FOREIGN KEY (thread_id) REFERENCES Threads(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES Posts(id) ON DELETE CASCADE
);

CREATE TABLE Corrections (
    orig_id INT UNSIGNED NOT NULL,
    post_id INT UNSIGNED NOT NULL PRIMARY KEY,
    FOREIGN KEY (orig_id) REFERENCES Originals(post_id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES Posts(id) ON DELETE CASCADE
);